//! Decoder vs the Python oracle.
//!
//! Fixtures: `tests/oracle/mod.rs`, generated by
//!     python3 hub75/fixtures/gen_oracle.py hub75/tests/oracle/mod.rs
//! from `AnimatedPixelClock-twin/tools/twin/research/model.py` (the research re-implementation
//! of the library 3.0.14 buffer build plus its reference decoder).
//!
//! Each scenario is rebuilt here with `hub75::refmodel` and must hash to the same word stream
//! as the oracle's before its decode is compared, so both sides decode identical input.

mod oracle;

use hub75::refmodel::{DmaChains, LibModel, LUM_CONV_TAB_8BIT};
use hub75::{decode_chain, ColumnOrder, Decoder, DecoderConfig, LatchMode, Refresh};

fn fnv1a64(bytes: impl IntoIterator<Item = u8>) -> u64 {
    let mut h = 0xcbf2_9ce4_8422_2325u64;
    for b in bytes {
        h ^= b as u64;
        h = h.wrapping_mul(0x100_0000_01b3);
    }
    h
}

fn stream_fnv(words: &[u16]) -> u64 {
    fnv1a64(words.iter().flat_map(|w| w.to_le_bytes()))
}

fn onclk_fnv(r: &Refresh) -> u64 {
    fnv1a64(r.on_clk.iter().flat_map(|c| c.iter().flat_map(|v| v.to_le_bytes())))
}

fn lit(r: &Refresh) -> Vec<(u16, u16, [u32; 3])> {
    let mut v = Vec::new();
    for y in 0..r.height {
        for x in 0..r.width {
            let c = r.get(x, y);
            if c != [0, 0, 0] {
                v.push((y as u16, x as u16, c));
            }
        }
    }
    v
}

/// The oracle's buffer: model.clear_fb + set_brightness + paint, i.e. the library after
/// resetbuffers(), setBrightness(brt) and drawPixel calls into buffer 0.
fn build(brightness: u8, fill: Option<[u8; 3]>, paints: &[(u16, u16, u8, u8, u8)]) -> LibModel {
    let mut m = LibModel::new(128, 64, 8, 8_000_000, 2, 60);
    m.set_brightness(brightness);
    if let Some([r, g, b]) = fill {
        for y in 0..64 {
            for x in 0..128 {
                m.draw_pixel(0, x, y, r, g, b);
            }
        }
    }
    for &(x, y, r, g, b) in paints {
        m.draw_pixel(0, x as usize, y as usize, r, g, b);
    }
    m
}

fn decode_buf(m: &LibModel, buf: usize, cfg: &DecoderConfig) -> Refresh {
    decode_chain(cfg, &m.segments(buf))
}

#[test]
fn cie_lut_is_the_one_the_oracle_parsed() {
    assert_eq!(LUM_CONV_TAB_8BIT, oracle::LUT);
    // cie_luts.h generator formula (research F13, verified 256/256 by the research): spot values
    assert_eq!((LUM_CONV_TAB_8BIT[4], LUM_CONV_TAB_8BIT[5], LUM_CONV_TAB_8BIT[128], LUM_CONV_TAB_8BIT[192]), (0, 1, 47, 124));
}

#[test]
fn library_setup_matches_oracle() {
    let m = LibModel::firmware();
    assert_eq!(m.lsb_msb_transition_bit, oracle::T);
    assert_eq!(m.calculated_refresh_rate, oracle::CALC_REFRESH_HZ as i64);
    let seq: Vec<u8> = m.segment_planes().iter().map(|&p| p as u8).collect();
    assert_eq!(seq, oracle::SEQ);
    let d = m.descriptors();
    assert_eq!(d.len(), 512, "16 descriptors per row x 32 rows");
    assert_eq!(d.iter().filter(|x| x.suc_eof).count(), 1);
    assert!(d.last().unwrap().suc_eof);
    assert_eq!(d.iter().map(|x| x.len).sum::<usize>(), 94_208);
}

#[test]
fn oe_windows_match_oracle() {
    for &(brt, counts) in oracle::OE_COUNTS {
        let mut m = LibModel::firmware();
        m.set_brightness(brt);
        for row in [0, 17, 31] {
            let mut got = [0u32; 8];
            for (p, g) in got.iter_mut().enumerate() {
                *g = m.plane_mut(0, row, p).iter().filter(|w| **w & 0x80 == 0).count() as u32;
            }
            assert_eq!(got, counts, "brightness {brt} row {row}");
        }
    }
}

#[test]
fn every_scenario_decodes_like_the_oracle() {
    let cfg = DecoderConfig::default();
    for sc in oracle::SCENARIOS {
        let m = build(sc.brightness, sc.fill, sc.paints);
        let s = m.stream(0);
        assert_eq!(s.len(), sc.stream_len, "{}", sc.name);
        assert_eq!(stream_fnv(&s), sc.stream_fnv, "{}: rebuilt stream differs from the oracle's", sc.name);
        let r = decode_buf(&m, 0, &cfg);
        assert_eq!(r.total_clocks, sc.total, "{}", sc.name);
        let l = lit(&r);
        assert_eq!(l.len(), sc.lit_count, "{}", sc.name);
        if !sc.lit.is_empty() {
            assert_eq!(l, sc.lit, "{}", sc.name);
        }
        assert_eq!(onclk_fnv(&r), sc.onclk_fnv, "{}: on-clocks differ from the oracle's", sc.name);
    }
}

fn scenario(name: &str) -> &'static oracle::Scenario {
    oracle::SCENARIOS.iter().find(|s| s.name == name).unwrap()
}

#[test]
fn white_255_is_2626_clocks_in_a_94208_word_frame() {
    let sc = scenario("white_255");
    let m = build(sc.brightness, sc.fill, sc.paints);
    let r = decode_buf(&m, 0, &DecoderConfig::default());
    assert_eq!(r.total_clocks, 94_208);
    assert!(r.on_clk.iter().all(|c| *c == [2626, 2626, 2626]));
    // 23 segments per row x 32 rows; LAT on word 127 of each (.cpp:645)
    assert_eq!(r.latches, 23 * 32);
}

#[test]
fn white_50_is_500_clocks() {
    let sc = scenario("white_50");
    let m = build(sc.brightness, sc.fill, sc.paints);
    let r = decode_buf(&m, 0, &DecoderConfig::default());
    assert!(r.on_clk.iter().all(|c| *c == [500, 500, 500]));
}

#[test]
fn library_fill_gives_the_same_stream_as_painting_every_pixel() {
    let mut a = LibModel::firmware();
    a.set_brightness(255);
    a.fill(0, 255, 255, 255);
    assert_eq!(stream_fnv(&a.stream(0)), scenario("white_255").stream_fnv);
}

fn ramp_reds(name: &str) -> Vec<u32> {
    let sc = scenario(name);
    let m = build(sc.brightness, sc.fill, sc.paints);
    let r = decode_buf(&m, 0, &DecoderConfig::default());
    let reds: Vec<u32> = (0..15).map(|x| r.get(x, 3)[0]).collect();
    assert_eq!(sc.lit.iter().map(|l| l.2[0]).collect::<Vec<_>>(), reds, "{name}");
    reds
}

#[test]
fn ramp_186_200_has_the_193_194_dip() {
    let r255 = ramp_reds("ramp_186_200_255");
    // research F11 / check2.py output, reproduced: input 193 = 1478 clocks, 194 = 1134
    assert_eq!(r255, [1304, 1322, 1352, 1386, 1400, 1430, 1448, 1478, 1134, 1148, 1178, 1196, 1226, 1260, 1290]);
    let r50 = ramp_reds("ramp_186_200_50");
    for reds in [&r255, &r50] {
        assert!(reds[7] > reds[8], "code 193 (x=7) must be brighter than 194 (x=8): {reds:?}");
    }
}

#[test]
fn plane_weights_are_non_binary_like_the_oracle() {
    for &(brt, weights) in oracle::PLANE_WEIGHTS {
        let mut got = [0u32; 8];
        for (p, g) in got.iter_mut().enumerate() {
            let mut m = LibModel::firmware();
            m.set_brightness(brt);
            m.plane_mut(0, 10, p)[10] |= 1; // model.py:105: red bit of plane p, pixel (10,10)
            let r = decode_buf(&m, 0, &DecoderConfig::default());
            *g = r.get(10, 10)[0];
            assert_eq!(lit(&r).len(), 1, "no leakage");
        }
        assert_eq!(got, weights, "brightness {brt}");
    }
}

#[test]
fn single_pixels_land_on_their_leds() {
    let sc = scenario("positions_255");
    let m = build(sc.brightness, sc.fill, sc.paints);
    let r = decode_buf(&m, 0, &DecoderConfig::default());
    let f = 2626;
    assert_eq!(r.get(0, 0), [0, 0, f]); // corner, block 0 whose plane 0 carries address 31
    assert_eq!(r.get(127, 0), [f, 0, 0]); // corner, word 127 = the LAT word
    assert_eq!(r.get(0, 63), [0, f, 0]); // corner, lower half
    assert_eq!(r.get(127, 63), [f, f, f]); // corner
    assert_eq!(r.get(5, 31), [f, 0, 0]); // last upper row
    assert_eq!(r.get(6, 32), [0, 0, f]); // first lower row
    assert_eq!(r.get(63, 31), [f, f, f]); // panel seam
    assert_eq!(r.get(64, 32), [f, f, f]);
    assert_eq!(lit(&r).len(), sc.paints.len(), "nothing leaks into other LEDs");
}

#[test]
fn double_buffer_flip_lands_at_the_chain_wrap_like_the_oracle() {
    let mut m = LibModel::firmware();
    m.set_brightness(255);
    for &(x, y, r, g, b) in oracle::FLIP_A {
        m.draw_pixel(0, x as usize, y as usize, r, g, b);
    }
    for &(x, y, r, g, b) in oracle::FLIP_B {
        m.draw_pixel(1, x as usize, y as usize, r, g, b);
    }
    assert_eq!(stream_fnv(&m.stream(0)), oracle::FLIP_A_STREAM_FNV);
    assert_eq!(stream_fnv(&m.stream(1)), oracle::FLIP_B_STREAM_FNV);

    let mut chains = DmaChains::new(&m); // begin(): chain A loops, GDMA at _dmadesc_a[0]
    let mut dec = Decoder::new(DecoderConfig::default());
    let mut refreshes = Vec::new();
    let mut steps = 0usize;
    while refreshes.len() < 4 {
        // display() with back_buffer_id 1, issued in the middle of the second pass of A:
        // only the last descriptor's `next` changes, so B starts at the next wrap.
        if steps == 512 + 200 {
            chains.flip(1);
        }
        let (words, eof) = chains.step(&m);
        steps += 1;
        if let Some(r) = dec.feed_segment(words, eof) {
            refreshes.push(r);
        }
    }
    // refreshes[0] is the cold start (empty shift register); 1..3 = oracle passes 1..3
    for (i, (total, want)) in oracle::FLIP_REFRESHES.iter().enumerate() {
        let r = &refreshes[i + 1];
        assert_eq!(r.total_clocks, *total);
        assert_eq!(lit(r), *want, "refresh {}", i + 1);
    }
    // the tear: first B refresh still shows A's row-31 plane-7 data for one W0 = 126 clocks
    assert_eq!(refreshes[2].get(10, 31), [126, 0, 0]);
    assert_eq!(refreshes[2].get(20, 31), [2500, 2500, 2500]);
}

#[test]
fn falling_edge_latch_is_identical_on_the_library_stream() {
    let sc = scenario("gradient_255");
    let m = build(sc.brightness, sc.fill, sc.paints);
    let level = decode_buf(&m, 0, &DecoderConfig::default());
    let falling = decode_buf(&m, 0, &DecoderConfig { latch: LatchMode::FallingEdge, ..Default::default() });
    assert_eq!(level, falling);
}

#[test]
fn rising_edge_latch_moves_the_image_one_column() {
    let sc = scenario("positions_255");
    let m = build(sc.brightness, sc.fill, sc.paints);
    let r = decode_buf(&m, 0, &DecoderConfig { latch: LatchMode::RisingEdge, ..Default::default() });
    assert_eq!(r.get(10, 10), [0, 0, 0]);
    assert_eq!(r.get(11, 10), [2626, 0, 0]);
    assert_eq!(r.get(21, 42), [0, 2626, 0]);
}

#[test]
fn column_order_options() {
    let sc = scenario("positions_255");
    let m = build(sc.brightness, sc.fill, sc.paints);
    let rev = decode_buf(&m, 0, &DecoderConfig { columns: ColumnOrder::Reversed, ..Default::default() });
    assert_eq!(rev.get(127 - 10, 10), [2626, 0, 0]);
    let swap = decode_buf(&m, 0, &DecoderConfig { columns: ColumnOrder::ReversePanelOrder { panel_width: 64 }, ..Default::default() });
    assert_eq!(swap.get(74, 10), [2626, 0, 0]);
    assert_eq!(swap.get(63, 63), [2626, 2626, 2626]); // x=127 -> panel 1 becomes panel 0
}

#[test]
fn streaming_in_odd_chunks_equals_whole_segments() {
    let sc = scenario("gradient_255");
    let m = build(sc.brightness, sc.fill, sc.paints);
    let s = m.stream(0);
    let mut d = Decoder::new(DecoderConfig::default());
    d.feed(&s);
    d.end_refresh();
    for c in s.chunks(37) {
        d.feed(c);
    }
    let r = d.end_refresh();
    assert_eq!(onclk_fnv(&r), sc.onclk_fnv);
    assert_eq!(r.index, 1);
}
